# Generated by Django 4.2.8 on 2024-09-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filtering", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.IntegerField(),
        ),
    ]
