# Generated by Django 4.2.8 on 2024-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_authn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="passby",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
