# Generated by Django 4.2.8 on 2024-09-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("p_id", models.IntegerField()),
                ("address", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=10)),
            ],
        ),
    ]
